//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int IdDetalleVenta { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> IdSucursalProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual SucursalProducto SucursalProducto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
